name: stfb-raw-proxy-tof
defaults:
  stfb_dataspec: "A:TOF/RAWDATA/768\\;B:TOF/RAWDATA/1024\\;C:TOF/RAWDATA/1280\\;D:TOF/RAWDATA/1536"
  user: flp
control:
  mode: "fairmq"
wants:
  cpu: 0.15
  memory: 128
bind:
  - name: from_readout-proxy_to_tof-compressor-0
    type: push
    transport: shmem
    addressing: ipc
    rateLogging: "60"
  - name: from_readout-proxy_to_tof-compressor-1
    type: push
    transport: shmem
    addressing: ipc
    rateLogging: "60"
  - name: from_readout-proxy_to_tof-compressor-2
    type: push
    transport: shmem
    addressing: ipc
    rateLogging: "60"
  - name: from_readout-proxy_to_tof-compressor-3
    type: push
    transport: shmem
    addressing: ipc
    rateLogging: "60"
command:
  shell: true
  value: >-
    eval `aliswmod load O2 Control-OCCPlugin` &&
    cat {{dpl_config}} | o2-dpl-raw-proxy
  user: "{{ user }}"
  arguments:
    - "-b"
    - "--monitoring-backend"
    - "{{ monitoring_qc_url }}"
    - "--id"
    - "readout-proxy"
    - "--log-color"
    - "false"
    - "--dataspec"
    - "{{ stfb_dataspec }}"
    - "--readers"
    - "1"
    - "--start-value-enumeration"
    - "0"
    - "--step-value-enumeration"
    - "1"
    - "--end-value-enumeration"
    - "-1"
    - "--session"
    - "default"
    - "--shm-monitor false"
